# Generated by Django 5.1 on 2024-09-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(default='Default summary', max_length=1000),
            preserve_default=False,
        ),
    ]
